import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { cleanHeroLine } from './clean-hero-line.mjs';

const INCOMING_DIR = path.resolve('assets/incoming');
const OUTPUT_DIR = path.resolve('public/assets');
const GENERATED_TS_PATH = path.resolve('src/data/assets.generated.ts');

const TARGET_WIDTHS = [1080, 1536];

const ASSETS = [
  { id: 'hero-photo', filename: 'hero-photo.jpg', clean: false },
  { id: 'hero-line', filename: 'hero-line.jpg', clean: true },
  { id: 'plate-01', filename: 'plate-01.jpg', clean: false },
  { id: 'plate-48', filename: 'plate-48.jpg', clean: false },
  { id: 'plate-96', filename: 'plate-96.jpg', clean: false },
  { id: 'plate-144', filename: 'plate-144.jpg', clean: false },
];

/**
 * Format bytes to readable string (KB, MB)
 */
function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

async function optimizeAssets() {
  console.log('=== The Spiral: Asset Optimization Pipeline ===');
  console.log(`Source directory: ${INCOMING_DIR}`);
  console.log(`Output directory: ${OUTPUT_DIR}`);
  console.log(`Target widths: ${TARGET_WIDTHS.join(', ')}px`);

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const generatedManifest = {};
  let totalBytes = 0;
  let fileCount = 0;

  for (const asset of ASSETS) {
    const inputPath = path.join(INCOMING_DIR, asset.filename);
    if (!fs.existsSync(inputPath)) {
      throw new Error(`Missing source file: ${inputPath}`);
    }

    console.log(`\nProcessing [${asset.id}] from ${asset.filename}...`);

    let baseBuffer;
    if (asset.clean) {
      console.log(`  Applying clean-hero-line mask rectangles...`);
      const cleaned = await cleanHeroLine(inputPath);
      baseBuffer = await cleaned.toBuffer();
    } else {
      baseBuffer = await sharp(inputPath).toBuffer();
    }

    const meta = await sharp(baseBuffer).metadata();
    const sourceWidth = meta.width;
    const sourceHeight = meta.height;
    const aspect = Number((sourceWidth / sourceHeight).toFixed(10));

    console.log(`  Source dimensions: ${sourceWidth}x${sourceHeight} (aspect: ${aspect})`);

    const avifSources = [];
    const webpSources = [];
    const jpegSources = [];

    for (const width of TARGET_WIDTHS) {
      // Never upscale beyond source
      if (width > sourceWidth) continue;

      const resizeOpts = { width, withoutEnlargement: true };

      // 1. AVIF (quality 50)
      const avifFilename = `${asset.id}-${width}.avif`;
      const avifPath = path.join(OUTPUT_DIR, avifFilename);
      const avifBuffer = await sharp(baseBuffer)
        .resize(resizeOpts)
        .avif({ quality: 50, effort: 4 })
        .toBuffer();
      fs.writeFileSync(avifPath, avifBuffer);
      avifSources.push(`/assets/${avifFilename} ${width}w`);
      totalBytes += avifBuffer.length;
      fileCount++;
      console.log(`  ✓ ${avifFilename.padEnd(24)} ${formatBytes(avifBuffer.length)}`);

      // 2. WebP (quality 72)
      const webpFilename = `${asset.id}-${width}.webp`;
      const webpPath = path.join(OUTPUT_DIR, webpFilename);
      const webpBuffer = await sharp(baseBuffer)
        .resize(resizeOpts)
        .webp({ quality: 72, effort: 4 })
        .toBuffer();
      fs.writeFileSync(webpPath, webpBuffer);
      webpSources.push(`/assets/${webpFilename} ${width}w`);
      totalBytes += webpBuffer.length;
      fileCount++;
      console.log(`  ✓ ${webpFilename.padEnd(24)} ${formatBytes(webpBuffer.length)}`);

      // 3. JPEG (quality 80)
      const jpegFilename = `${asset.id}-${width}.jpg`;
      const jpegPath = path.join(OUTPUT_DIR, jpegFilename);
      const jpegBuffer = await sharp(baseBuffer)
        .resize(resizeOpts)
        .jpeg({ quality: 80, mozjpeg: true })
        .toBuffer();
      fs.writeFileSync(jpegPath, jpegBuffer);
      jpegSources.push(`/assets/${jpegFilename} ${width}w`);
      totalBytes += jpegBuffer.length;
      fileCount++;
      console.log(`  ✓ ${jpegFilename.padEnd(24)} ${formatBytes(jpegBuffer.length)}`);
    }

    generatedManifest[asset.id] = {
      avif: avifSources.join(', '),
      webp: webpSources.join(', '),
      jpeg: jpegSources.join(', '),
      fallback: `/assets/${asset.id}-1536.jpg`,
      width: sourceWidth,
      height: sourceHeight,
      aspect,
    };
  }

  // Generate src/data/assets.generated.ts
  const tsContent = `// Auto-generated by scripts/optimize-assets.mjs - DO NOT EDIT MANUALLY

export interface AssetSourceSet {
  avif: string;
  webp: string;
  jpeg: string;
  fallback: string;
  width: number;
  height: number;
  aspect: number;
}

export type AssetName =
  | 'hero-photo'
  | 'hero-line'
  | 'plate-01'
  | 'plate-48'
  | 'plate-96'
  | 'plate-144';

export type LevelId = 'L1' | 'L48' | 'L96' | 'L144';

export const ASSETS: Record<AssetName, AssetSourceSet> = ${JSON.stringify(
    generatedManifest,
    null,
    2
  )};

export const LEVEL_PLATES: Record<LevelId, AssetSourceSet> = {
  L1: ASSETS['plate-01'],
  L48: ASSETS['plate-48'],
  L96: ASSETS['plate-96'],
  L144: ASSETS['plate-144'],
};

export const HERO_LINE: AssetSourceSet = ASSETS['hero-line'];
export const HERO_PHOTO: AssetSourceSet = ASSETS['hero-photo'];
`;

  const tsDir = path.dirname(GENERATED_TS_PATH);
  if (!fs.existsSync(tsDir)) {
    fs.mkdirSync(tsDir, { recursive: true });
  }

  fs.writeFileSync(GENERATED_TS_PATH, tsContent, 'utf-8');
  console.log(`\nExported source sets to ${GENERATED_TS_PATH}`);
  console.log(`Optimization complete: ${fileCount} files generated, total ${formatBytes(totalBytes)}.`);
}

optimizeAssets().catch((err) => {
  console.error('\n[optimize-assets] Error during optimization:', err);
  process.exit(1);
});
