// Auto-generated by scripts/optimize-assets.mjs - DO NOT EDIT MANUALLY

export interface AssetSourceSet {
  avif: string;
  webp: string;
  jpeg: string;
  fallback: string;
  width: number;
  height: number;
  aspect: number;
}

export type AssetName =
  | 'hero-photo'
  | 'hero-line'
  | 'plate-01'
  | 'plate-48'
  | 'plate-96'
  | 'plate-144';

export type LevelId = 'L1' | 'L48' | 'L96' | 'L144';

export const ASSETS: Record<AssetName, AssetSourceSet> = {
  "hero-photo": {
    "avif": "/assets/hero-photo-1080.avif 1080w, /assets/hero-photo-1536.avif 1536w",
    "webp": "/assets/hero-photo-1080.webp 1080w, /assets/hero-photo-1536.webp 1536w",
    "jpeg": "/assets/hero-photo-1080.jpg 1080w, /assets/hero-photo-1536.jpg 1536w",
    "fallback": "/assets/hero-photo-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  },
  "hero-line": {
    "avif": "/assets/hero-line-1080.avif 1080w, /assets/hero-line-1536.avif 1536w",
    "webp": "/assets/hero-line-1080.webp 1080w, /assets/hero-line-1536.webp 1536w",
    "jpeg": "/assets/hero-line-1080.jpg 1080w, /assets/hero-line-1536.jpg 1536w",
    "fallback": "/assets/hero-line-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  },
  "plate-01": {
    "avif": "/assets/plate-01-1080.avif 1080w, /assets/plate-01-1536.avif 1536w",
    "webp": "/assets/plate-01-1080.webp 1080w, /assets/plate-01-1536.webp 1536w",
    "jpeg": "/assets/plate-01-1080.jpg 1080w, /assets/plate-01-1536.jpg 1536w",
    "fallback": "/assets/plate-01-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  },
  "plate-48": {
    "avif": "/assets/plate-48-1080.avif 1080w, /assets/plate-48-1536.avif 1536w",
    "webp": "/assets/plate-48-1080.webp 1080w, /assets/plate-48-1536.webp 1536w",
    "jpeg": "/assets/plate-48-1080.jpg 1080w, /assets/plate-48-1536.jpg 1536w",
    "fallback": "/assets/plate-48-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  },
  "plate-96": {
    "avif": "/assets/plate-96-1080.avif 1080w, /assets/plate-96-1536.avif 1536w",
    "webp": "/assets/plate-96-1080.webp 1080w, /assets/plate-96-1536.webp 1536w",
    "jpeg": "/assets/plate-96-1080.jpg 1080w, /assets/plate-96-1536.jpg 1536w",
    "fallback": "/assets/plate-96-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  },
  "plate-144": {
    "avif": "/assets/plate-144-1080.avif 1080w, /assets/plate-144-1536.avif 1536w",
    "webp": "/assets/plate-144-1080.webp 1080w, /assets/plate-144-1536.webp 1536w",
    "jpeg": "/assets/plate-144-1080.jpg 1080w, /assets/plate-144-1536.jpg 1536w",
    "fallback": "/assets/plate-144-1536.jpg",
    "width": 1536,
    "height": 2752,
    "aspect": 0.5581395349
  }
};

export const LEVEL_PLATES: Record<LevelId, AssetSourceSet> = {
  L1: ASSETS['plate-01'],
  L48: ASSETS['plate-48'],
  L96: ASSETS['plate-96'],
  L144: ASSETS['plate-144'],
};

export const HERO_LINE: AssetSourceSet = ASSETS['hero-line'];
export const HERO_PHOTO: AssetSourceSet = ASSETS['hero-photo'];
